name: generate-snake-game-from-github-contribution-grid
# GitHub Action, katkılarınızla yılan oyunu oluşturur.

# Bu eylemin ne zaman çalışacağını kontrol eder. Bu eylem her 6 saatte bir çalışır.
on:
  schedule:
    # her 6 saatte bir
    - cron: "0 */6 * * *"

  # Bu komut, eylemi Actions sekmesinden otomatik olarak çalıştırmamızı sağlar.
  workflow_dispatch:

# Bu iş akışındaki işlemlerin sırası:
jobs:
  # Bu iş akışı "build" adlı tek bir iş içerir
  build:
    # İşin çalışacağı koşucu türü
    runs-on: ubuntu-latest

    # İşin bir parçası olarak gerçekleştirilecek görevler dizisini temsil eden adımlar
    steps:
      # Depoyu $GITHUB_WORKSPACE altında kontrol eder, böylece işiniz ona erişebilir
      - uses: actions/checkout@v2

      # Yılanı oluşturur
      - uses: Platane/snk@v3.2.0
        id: snake-gif
        with:
          github_user_name: busekosee
          # Bu sonraki 2 satır dosyaları "output" adlı bir dalda oluşturur. Bu, ana dalın dağınıklıktan uzak kalmasını sağlar.
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # İşlem durumunu gösterir. Herhangi bir sorun varsa hata ayıklamayı kolaylaştırır.
      - run: git status

      # Değişiklikleri push yap
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      # GitHub Pages'e dağıtım yap
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
